version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: mkdir -p output
          name: Create directory
      - run:
          command: touch output/foo
          name: Create foo
      - run:
          command: touch output/bar
          name: Create bar
      - store_artifacts:
          path: output
