version: 2
jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: mkdir -p output
          name: Create directory
      - run:
          command: echo "Foo" > output/foo
          name: Create foo
      - run:
          command: echo "Bar" > output/bar
          name: Create bar
      - store_artifacts:
          path: output
